### PR TITLE
move choose_rand into a blanket impl of Set

### PR DESCRIPTION
**Pull request by chromebookerg**

### CODE REVIEW

**Comment by HyperCodec** [comment]
`cargo test` errored because it hasn't been updated, make sure to fix that first.

**Comment by chromebookerg** [comment]
done, although i won't be updating your docs, you will have to do that yourself.

**Comment by HyperCodec** [comment]
Also build failed btw

**Comment by HyperCodec** [comment]
Are you not using an ide? Check if it compiles before pushing code.

**Pull request closed without merging**
